"use client";

import { useEffect, useState, use } from "react";
import { doc, getDoc, Timestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";

type Incident = Record<string, unknown> & {
  createdAt?: Timestamp;
  emergencyType?: string;
  severity?: number;
  roomNumber?: string;
};

export default function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [incident, setIncident] = useState<Incident | null>(null);
  const [markdown, setMarkdown] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const snap = await getDoc(doc(db, "incidents", id));
        if (!snap.exists()) throw new Error("Incident not found");
        const data = { id: snap.id, ...snap.data() } as Incident;
        setIncident(data);

        const res = await fetch("/api/report", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            incident: {
              ...data,
              createdAt: data.createdAt instanceof Timestamp
                ? data.createdAt.toDate().toISOString()
                : data.createdAt,
            },
          }),
        });
        if (!res.ok) throw new Error(`Report gen failed: ${res.status}`);
        const { markdown } = await res.json();
        setMarkdown(markdown);
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Failed to load");
      } finally {
        setLoading(false);
      }
    })();
  }, [id]);

  return (
    <div className="mx-auto max-w-3xl px-6 py-10">
      <div className="no-print mb-6 flex items-center justify-between">
        <div>
          <div className="text-xs font-mono tracking-widest text-emerald-400">AFTER — INCIDENT REPORT</div>
          <h1 className="text-3xl font-semibold">Compliance Report</h1>
        </div>
        <button
          onClick={() => window.print()}
          className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-zinc-200"
        >
          Download PDF
        </button>
      </div>

      {loading && <div className="card p-8 text-center text-zinc-400">Generating with Gemini…</div>}
      {error && <div className="card border-red-500/40 bg-red-500/10 p-6 text-red-300">{error}</div>}

      {incident && (
        <div className="card p-8">
          <div className="mb-6 border-b border-white/10 pb-4">
            <div className="text-xs uppercase tracking-wide text-zinc-400">Incident ID</div>
            <div className="font-mono text-sm">{id}</div>
            <div className="mt-3 grid grid-cols-3 gap-4 text-sm">
              <div>
                <div className="text-xs text-zinc-400">Type</div>
                <div className="font-semibold">{incident.emergencyType || "—"}</div>
              </div>
              <div>
                <div className="text-xs text-zinc-400">Severity</div>
                <div className="font-semibold">{incident.severity ?? "—"}/5</div>
              </div>
              <div>
                <div className="text-xs text-zinc-400">Location</div>
                <div className="font-semibold">Room {incident.roomNumber || "—"}</div>
              </div>
            </div>
          </div>

          <article className="prose prose-invert prose-sm max-w-none report-md">
            <SimpleMarkdown source={markdown} />
          </article>

          <div className="mt-8 border-t border-white/10 pt-4 text-xs text-zinc-500">
            Generated by SahayakAI • Gemini 1.5 Flash • {new Date().toLocaleString()}
          </div>
        </div>
      )}

      <style jsx global>{`
        .report-md h2 { font-size: 1.25rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.5rem; color: #f4f6f8; }
        .report-md p { margin: 0.5rem 0; color: #d4d4d8; line-height: 1.6; }
        .report-md ul { margin: 0.5rem 0 0.5rem 1.25rem; list-style: disc; color: #d4d4d8; }
        .report-md li { margin: 0.25rem 0; }
        .report-md strong { color: #fff; }
        @media print {
          .report-md h2 { color: black; }
          .report-md p, .report-md ul, .report-md li { color: #222; }
        }
      `}</style>
    </div>
  );
}

function SimpleMarkdown({ source }: { source: string }) {
  if (!source) return null;
  const html = source
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*?<\/li>\n?)+/gs, (m) => `<ul>${m}</ul>`)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .split(/\n\n+/)
    .map((block) => (block.startsWith("<") ? block : `<p>${block.replace(/\n/g, " ")}</p>`))
    .join("\n");
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
